### PR TITLE
Ensure ip is updated/deleted

### LINKED ISSUE #42: Tag deletion can go wrong
Seems like it's possible that a tag deletion on an IP address fails and then the IP address will stick with this tag for the rest of its allocation time.

Is there a way we can reconcile the tag state of IP addresses?

### PR DESCRIPTION
**Pull request by majst01**
closes #42

### CODE REVIEW

File: pkg/controllers/loadbalancer/loadbalancer.go [hunk 1]
```diff
@@ -217,22 +218,35 @@ func (l *LoadBalancerController) EnsureLoadBalancerDeleted(ctx context.Context,
...
+					IPAddress: *ip.Ipaddress,
+					Tags:      newTags,
+				}
+				newIP, err := l.client.IPUpdate(iu)
+				if err != nil {
+					return fmt.Errorf("could not update ip with new tags: %w", err)
+				}
+				l.logger.Printf("updated ip: %v", newIP)
+				if *ip.Type == metalgo.IPTypeEphemeral && last {
+					err := metal.FreeIP(l.client, *ip.Ipaddress)
```
Comment (Gerrit91) [inline pkg/controllers/loadbalancer/loadbalancer.go:240]: Can we add another log line here?

```suggestion
					l.logger.Printf("freeing unused ephemeral ip: %s, tags: %s", *ip.Ipaddress, newTags)
					err := metal.FreeIP(l.client, *ip.Ipaddress)
```

**Review by Gerrit91 — APPROVED** [review]
